# Generated by Django 3.1.2 on 2020-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HybridClassroom',
            fields=[
                ('session_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_red', models.IntegerField(default=0)),
                ('color_green', models.IntegerField(default=0)),
                ('color_blue', models.IntegerField(default=0)),
                ('hand_raised', models.BooleanField(default=False)),
                ('understanding', models.BooleanField(null=True)),
                ('applause', models.BooleanField(default=False)),
                ('high_five', models.BooleanField(default=False)),
            ],
        ),
    ]
