# Generated by Django 3.1.2 on 2020-12-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_hybridclassroom_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridclassroom',
            name='animal',
            field=models.CharField(default='', max_length=200),
        ),
    ]
