# Generated by Django 3.1.2 on 2020-12-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridclassroom',
            name='negative',
            field=models.BooleanField(default=False),
        ),
    ]
